// import type { Metadata } from "next";
// import Header from "@/components/Shared/Header";
// import Footer from "@/components/Shared/Footer";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <div>
//       <Header />
//       {children}
//       <Footer />
//     </div>
//   );
// }


import type { Metadata } from "next";
import Header from "@/components/Shared/Header";
import Footer from "@/components/Shared/Footer";

export const metadata: Metadata = {
  title: "Hatem E-commerce",
  description: "Generated by create next app",
};

// ✅ Type-safe layout component
export default function WithLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="min-h-screen flex flex-col">
      {/* Shared header */}
      <Header />

      {/* Main content area */}
      <main className="flex-1">{children}</main>

      {/* Shared footer */}
      <Footer />
    </div>
  );
}
